#!/bin/bash

cd ~
USER_HOME=$(pwd)
set -e

echo === Please enter your password to proceed with the setup
# No purple screens
export DEBIAN_FRONTEND=noninteractive

if [ -f /etc/needrestart/needrestart.conf ]; then
    sudo sed -i "s/#\$nrconf{restart} = 'i';/\$nrconf{restart} = 'a';/" /etc/needrestart/needrestart.conf
fi

echo === Now configuring swappiness
if grep -q "vm.swappiness=10" /etc/sysctl.conf; then
    echo "Swappiness already configured. Skipping."
else
    sudo sysctl vm.swappiness=10
    echo "vm.swappiness=10" | sudo tee -a /etc/sysctl.conf
fi
echo === Swappiness configured.

echo === Now installing Log2Ram to reduce SD card wear
sudo apt install -y curl gnupg
echo "deb [signed-by=/usr/share/keyrings/azlux-archive-keyring.gpg] http://packages.azlux.fr/debian/ bookworm main" | sudo tee /etc/apt/sources.list.d/azlux.list
sudo wget -O /usr/share/keyrings/azlux-archive-keyring.gpg https://azlux.fr/repo.gpg
sudo apt update
sudo apt install -y log2ram
sudo systemctl enable log2ram
sudo systemctl start log2ram
echo === Log2Ram installation complete.

mkdir -p ./xmrig
cd ./xmrig
echo "=== Now building XMRig from source"
# Temporarely straight up using Gemini generated code
echo ">> Installing build dependencies..."
# 安裝編譯所需的依賴庫 (libuv, ssl, hwloc 是必須的)
sudo apt update
sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev

echo ">> Fetching latest XMRig source..."
SRC_DIR="$USER_HOME/xmrig-src"
DEST_DIR="$USER_HOME/xmrig"

# 如果原始碼資料夾不存在就 Clone，存在就 Pull 更新
if [ ! -d "$SRC_DIR" ]; then
    git clone https://github.com/xmrig/xmrig.git "$SRC_DIR"
else
    cd "$SRC_DIR" && git pull
fi

# 進入編譯目錄
mkdir -p "$SRC_DIR/build"
cd "$SRC_DIR/build"

echo ">> Compiling XMRig. This may take a while."
# 配置 CMake
cmake ..
# 開始編譯 (使用所有 CPU 核心加速)
make -j$(nproc)

# 將編譯好的執行檔複製到目標資料夾
echo ">> Installing binary..."
mkdir -p "$DEST_DIR"
cp xmrig "$DEST_DIR/xmrig"

echo "=== XMRig build complete. Now generating execution script"
# ^ Generated by Gemini
cat <<EOF > $USER_HOME/start-xmrig.sh
#!/bin/bash
echo "[XMRIG] Waiting for internet connection..."
while ! ping -c 1 8.8.8.8 &> /dev/null; do
    echo "Network unreachable, retrying in 10s..."
    sleep 10
done
exec $USER_HOME/xmrig/xmrig -o stratum+ssl://rx.unmineable.com:4444 -k -u [coin]:[address].unmineable_miner_RPiSub#elce-axze --http-port=60070 -a rx
EOF
chmod +x $USER_HOME/start-xmrig.sh
<<'COMMENT'
if ! sudo crontab -l 2>/dev/null | grep -q "start-xmrig.sh"; then
    (sudo crontab -l 2>/dev/null; echo "@reboot $USER_HOME/start-xmrig.sh >> $USER_HOME/xmrig.log 2>&1") | sudo crontab -
    echo "Auto-start added to Root Crontab."
else
    echo "Crontab already configured. Skipping."
fi
COMMENT
echo "=== Configuring XMRig as a Systemd Service"

# 1. 建立 Systemd Service 檔案
# 注意：這裡設定了 Restart=always，挖礦程式掛掉會自動重啟
sudo bash -c "cat <<EOF > /etc/systemd/system/xmrig_miner.service
[Unit]
Description=XMRig Miner Service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$USER_HOME/xmrig
# 下面這行換成你的實際執行指令
ExecStart=$USER_HOME/xmrig/xmrig -o stratum+ssl://rx.unmineable.com:4444 -k -u [coin]:[address].unmineable_miner_RPiSub#elce-axze --http-port=60070 -a rx
Restart=always
RestartSec=10s
StandardOutput=append:$USER_HOME/xmrig.log
StandardError=append:$USER_HOME/xmrig.log

[Install]
WantedBy=multi-user.target
EOF"

# 2. 重新加載 Systemd 並啟用服務
sudo systemctl daemon-reload
sudo systemctl enable xmrig_miner.service
echo "=== Execution script generated"

cd
echo "=== Now installing Cockpit"
. /etc/os-release
sudo apt install -y -t ${VERSION_CODENAME}-backports cockpit || sudo apt install -y cockpit
echo === Cockpit installation complete.
IP_ADDR=$(ip route get 8.8.8.8 | awk '{for(i=1;i<=NF;i++) if ($i=="src") print $(i+1)}')

echo =================
echo =Setup complete!=
echo =================
touch lastword.txt
echo "You can access Cockpit by navigating to https:/$IP_ADDR/:9090." >> lastword.txt
echo "Don't forget to replace [coin] and [address] in start-xmrig.sh with your desired coin and wallet address before running the miner." >> lastword.txt
echo "You can paste your [coin]:[address] by editing the execution script located at $USER_HOME/start-xmrig.sh via Cockpit's terminal." >> lastword.txt
cat lastword.txt
echo The message has been saved to lastword.txt. You can watch it by running \"cat lastword.txt\".
echo Now starting self-destruction process of this script.
rm -- "$0"