#!/bin/bash

scriptDir=$(pwd)
cd ~
USER_HOME=$(pwd)
USER=$(whoami)
# set -e

echo === Please enter your password to proceed with the setup
sudo -v
# No purple screens
export DEBIAN_FRONTEND=noninteractive
if [ -f /etc/needrestart/needrestart.conf ]; then
    sudo sed -i "s/#\$nrconf{restart} = 'i';/\$nrconf{restart} = 'a';/" /etc/needrestart/needrestart.conf
fi

echo === Now configuring Wi-Fi
read -p "Please enter the name (SSID) of your Wi-Fi: " WIFI_SSID
read -s -p "Please enter your Wi-Fi Password (Password hidden): " WIFI_PASS
echo
WIFI_IFACE=$(ip a | grep -oP 'wlan[0-9]+' | head -1)
if [ -z "$WIFI_IFACE" ]; then
    echo "Warning: Wireless adapter (wlan0/wlan1 etc.) not detected. Assuming wired connection only."
else
    echo ">> Wireless adapter detected: $WIFI_IFACE"
    cat <<NETPLAN_CONFIG | sudo tee /etc/netplan/99-wifi-config.yaml > /dev/null
network:
  version: 2
  renderer: NetworkManager
  ethernets:
    eth0:
      dhcp4: true
      optional: true
    ens33:
      dhcp4: true
      optional: true
  wifis:
    $WIFI_IFACE:
      dhcp4: true
      access-points:
        "$WIFI_SSID":
          password: "$WIFI_PASS"
NETPLAN_CONFIG
    echo ">> Applying internet settings..."
    sudo netplan apply
    echo ">> Waiting Wi-Fi finishing connection (5s)..."
    sleep 5
    if ! ping -c 1 8.8.8.8 &> /dev/null; then
        echo "! Wi-Fi connection could be failed. Please check your SSID and password."
    else
        echo "O Wi-Fi connected successfully."
    fi
fi
echo === Wi-Fi configuration complete

echo === Now configuring swappiness and hugepages
if grep -q "vm.swappiness=10" /etc/sysctl.conf; then
    echo "Swappiness already configured. Skipping."
else
    sudo sysctl vm.swappiness=10
    echo "vm.swappiness=10" | sudo tee -a /etc/sysctl.conf
fi
if grep -q "vm.nr_hugepages=1280" /etc/sysctl.conf; then
    echo "HugePages already configured. Skipping."
else
    echo "vm.nr_hugepages=1280" | sudo tee -a /etc/sysctl.conf
fi
echo === Swappiness configured.

mkdir -p ./xmrig
cd ./xmrig
echo "=== Now building XMRig from source"
# Temporarely straight up using Gemini generated code
echo ">> Installing build dependencies..."
# 安裝編譯所需的依賴庫 (libuv, ssl, hwloc 是必須的)
sudo apt update
sudo apt install -y git build-essential cmake libuv1-dev libssl-dev libhwloc-dev

echo ">> Fetching latest XMRig source..."
SRC_DIR="$USER_HOME/xmrig-src"
DEST_DIR="$USER_HOME/xmrig"

# 如果原始碼資料夾不存在就 Clone，存在就 Pull 更新
if [ ! -d "$SRC_DIR" ]; then
    git clone https://github.com/xmrig/xmrig.git "$SRC_DIR"
else
    cd "$SRC_DIR" && git pull
fi

# 進入編譯目錄
mkdir -p "$SRC_DIR/build"
cd "$SRC_DIR/build"

echo ">> Compiling XMRig. This may take a while."
# 配置 CMake
cmake ..
# 開始編譯 (使用所有 CPU 核心加速)
make -j$(nproc)

# 將編譯好的執行檔複製到目標資料夾
echo ">> Installing binary..."
mkdir -p "$DEST_DIR"
cp xmrig "$DEST_DIR/xmrig"

echo "=== XMRig build complete. Now generating execution script"
# ^ Generated by Gemini
cat <<EOF > $USER_HOME/start-xmrig.sh
#!/bin/bash
export PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin
echo "[XMRIG] Waiting for internet connection..."
while ! ping -c 1 8.8.8.8 &> /dev/null; do
    echo "Network unreachable, retrying in 10s..."
    sleep 10
done
exec $USER_HOME/xmrig/xmrig -o stratum+ssl://rx.unmineable.com:4444 -k -u [coin]:[address].unmineable_miner_RPiSub#elce-axze --http-port=60070 -a rx
EOF
chmod +x $USER_HOME/start-xmrig.sh
<<'COMMENT'
if ! sudo crontab -l 2>/dev/null | grep -q "start-xmrig.sh"; then
    (sudo crontab -l 2>/dev/null; echo "@reboot $USER_HOME/start-xmrig.sh >> $USER_HOME/xmrig.log 2>&1") | sudo crontab -
    echo "Auto-start added to Root Crontab."
else
    echo "Crontab already configured. Skipping."
fi
COMMENT
echo "=== Configuring XMRig as a Systemd Service"

# v Gemini generated code
# 1. 建立 Systemd Service 檔案
# 注意：這裡設定了 Restart=always，挖礦程式掛掉會自動重啟
sudo bash -c "cat <<EOF > /etc/systemd/system/xmrig_miner.service
[Unit]
Description=XMRig Miner Service
After=network-online.target
Wants=network-online.target

[Service]
Type=simple
User=$USER
WorkingDirectory=$USER_HOME
ExecStart=$USER_HOME/start-xmrig.sh
Restart=always
RestartSec=10s
StandardOutput=append:$USER_HOME/xmrig.log
StandardError=append:$USER_HOME/xmrig.log

[Install]
WantedBy=multi-user.target
EOF"

# 2. 重新加載 Systemd 並啟用服務
sudo systemctl daemon-reload
sudo systemctl enable xmrig_miner.service
echo "=== Execution script generated"

cd
echo "=== Now installing Cockpit"
. /etc/os-release
sudo apt install -y -t ${VERSION_CODENAME}-backports cockpit || sudo apt install -y cockpit
echo === Cockpit installation complete.
IP_ADDR=$(ip route get 8.8.8.8 | awk '{for(i=1;i<=NF;i++) if ($i=="src") print $(i+1)}')
# ^ Gemini generated code

curl -fsSL https://tailscale.com/install.sh | sh

echo === Now installing Log2Ram to reduce SD card wear
sudo apt install -y curl gnupg
# echo "deb [signed-by=/usr/share/keyrings/azlux-archive-keyring.gpg] http://packages.azlux.fr/debian/ $(bash -c '. /etc/os-release; echo ${VERSION_CODENAME}') main" | sudo tee /etc/apt/sources.list.d/azlux.list
echo "deb [signed-by=/usr/share/keyrings/azlux-archive-keyring.gpg] http://packages.azlux.fr/debian/ stable main" | sudo tee /etc/apt/sources.list.d/azlux.list
sudo wget -O /usr/share/keyrings/azlux-archive-keyring.gpg  https://azlux.fr/repo.gpg
LOG2RAM_INSTALLED_FLAG=1
if sudo apt update; then
    sudo apt install -y log2ram
    sudo systemctl enable log2ram
    sudo systemctl start log2ram
    echo === Log2Ram installation complete.
else 
    LOG2RAM_INSTALLED_FLAG=0
    echo "=!= Failed to add Log2Ram repository. Skipping Log2Ram installation."
fi

echo
echo ┌───────────────────────┬───┬───┐
echo │ Login tailscale now　 │ _ │ X │
echo └───────────────────────┴───┴───┘
echo
sudo tailscale up

echo
echo ┌───────────────────┬───┬───┐
echo │ Setup complete!　 │ _ │ X │
echo └───────────────────┴───┴───┘
echo
cat <<EOF > lastword.txt
You can access Cockpit by navigating to https://$IP_ADDR:9090
Don't forget to replace [coin] and [address] in start-xmrig.sh with your desired coin and wallet address before running the miner.
You can paste your [coin]:[address] by editing the execution script located at $USER_HOME/start-xmrig.sh via Cockpit's terminal.
EOF
cat lastword.txt
cat <<EOF > chkip.sh
IP_ADDR=\$(ip route get 8.8.8.8 | awk '{for(i=1;i<=NF;i++) if (\$i=="src") print \$(i+1)}')
echo "Current IP Address: \$IP_ADDR"
echo "So you can connect cockpit at: https://\$IP_ADDR:9090"
EOF
if [ $LOG2RAM_INSTALLED_FLAG -eq 1 ]; then
    echo "Log2Ram was installed successfully. Your SD card lifespan should be improved."
else
    echo "Log2Ram installation was skipped due to ppa (software source anyway) issues. Your SD card lifespan may not be optimized."
    cat <<< "! Log2Ram is not installed. Please consider installing it manually to reduce SD card wear." >> lastword.txt
fi
chmod +x chkip.sh
echo The message has been saved to lastword.txt. You can check it again by running \"cat lastword.txt\".
echo Now starting self-destruction process of this script.
rm -- "$0" || rm -- "$scriptDir/$0" || rm $scriptDir/xmr-setup.sh || rm ./xmrsetup-headless/xmr-setup.sh || echo "Failed to delete setup script. Please delete it manually by running \"rm ./xmr-setup.sh\""